---
layout: cv
title: Rex Wight
---
# Rex Wight
Student of Physics

<div id="webaddress">
<a href="www.linkedin.com/in/rex-wight-4a17791aa">LinkedIn</a>
| <a href="rexjared86@gmail.com">rexjared86@gmail.com</a>
</div>


## Currently

Studying 

### Specialized in Physics

Emphasis: Computation


### Professionial Experience

#### _Robotics-based Reinforcement Learning Undergraduate Intern_ - Pacific Northwest National Laboratory

Aug 2022 – Dec 2022

-  Implemented reinforcement learning algorithms to train virtual robots with TensorFlow.
-  Built a wrapper for Google’s MuJoCo environments for PNNL’s learner ExaRL.
-  Optimized Actor-Critic models using parallel computing techniques to enhance training efficiency.
-  Designed and executed experimental tests to support research and performance analysis.

#### _Remote Instructor_ – Coding with Kids

Nov 2021 – Sep 2022

-  Instructed elementary and middle school students in programming fundamentals (e.g.,
loops, conditionals) via Zoom.
-  Collaborated with team to refine curriculum and enhance student engagement.
-  Fostered critical-thinking skills, inspiring 20+ students to pursue STEM projects.

#### _Machine Learning Intern_ - Technical University of Munich

Mar 2021 - Apr 2021

- Applied machine learning (Artificial Neural Networks and Convolutional Neural Networks) and numerical methods to compute thermal diffusivities of Uranium-Molybdenum alloys.
- Developed adaptable problem-solving strategies for complex scientific challenges.

#### _Software Intern_ - Belgium Nuclear Science Center

Aug 2020 - Sept 2020

- Reviewed and designed GUI for EFFTRAN, a Monte Carlo-based gamma-ray
spectrometry algorithm, improving usability.
- Developed a machine learning model to predict cladding thickness on irradiated fuel
plates.
- Wrote miscellaneous Python scripts for other projects as requested by my mentor.


### Skills

-  Python
-  TensorFlow
-  Pandas, NumPy, Matplotlib, etc.
-  JavaScript
-  HTML
-  CSS
-  VisualBasic.NET
-  Processing
-  Arduino
-  Robotics
-  Leadership


## Education

`September 2022 - now`
__Brigham Young University Idaho__


## Relevant Courses

-  Physics
-  Calculus
-  Linear Algebra
-  Quantum Computing
-  Chemistry
-  Biology


<!-- ### Footer

Last updated: May 2013 -->